export enum UserRoleEnum {
  CUSTOMER = 'CUSTOMER',
  ADMIN = 'ADMIN',
  COURIER = 'COURIER'
}

export enum LanguageEnum {
  UZ = 'UZ',
  RU = 'RU',
  EN = 'EN'
}

export enum OrderStatusEnum {
  PENDING = 'PENDING',
  PREPARING = 'PREPARING',
  READY_FOR_PICKUP = 'READY_FOR_PICKUP',
  DELIVERING = 'DELIVERING',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum PaymentMethodEnum {
  CASH = 'CASH',
  MANUAL_TRANSFER = 'MANUAL_TRANSFER',
  EXTERNAL_PAYMENT = 'EXTERNAL_PAYMENT'
}

export enum PaymentStatusEnum {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED'
}

export enum PromoDiscountTypeEnum {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT'
}

export enum NotificationTypeEnum {
  INFO = 'INFO',
  SUCCESS = 'SUCCESS',
  WARNING = 'WARNING',
  ERROR = 'ERROR',
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  PROMO_CAMPAIGN = 'PROMO_CAMPAIGN',
  ADMIN_NOTICE = 'ADMIN_NOTICE'
}

export enum AppEventEnum {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_CONFIRMED = 'ORDER_CONFIRMED',
  ORDER_PREPARING = 'ORDER_PREPARING',
  ORDER_READY_FOR_PICKUP = 'ORDER_READY_FOR_PICKUP',
  ORDER_PICKED_UP = 'ORDER_PICKED_UP',
  ORDER_DELIVERING = 'ORDER_DELIVERING',
  ORDER_DELIVERED = 'ORDER_DELIVERED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',

  PAYMENT_PENDING = 'PAYMENT_PENDING',
  PAYMENT_VERIFIED = 'PAYMENT_VERIFIED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',

  COURIER_ASSIGNED = 'COURIER_ASSIGNED',
  COURIER_UNASSIGNED = 'COURIER_UNASSIGNED',

  PROMO_CREATED = 'PROMO_CREATED',
  PROMO_EXPIRED = 'PROMO_EXPIRED'
}

export enum CourierAssignmentStatusEnum {
  ASSIGNED = 'ASSIGNED',
  REJECTED = 'REJECTED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum DeliveryStageEnum {
  IDLE = 'IDLE',
  GOING_TO_RESTAURANT = 'GOING_TO_RESTAURANT',
  ARRIVED_AT_RESTAURANT = 'ARRIVED_AT_RESTAURANT',
  PICKED_UP = 'PICKED_UP',
  DELIVERING = 'DELIVERING',
  ARRIVED_AT_DESTINATION = 'ARRIVED_AT_DESTINATION',
  DELIVERED = 'DELIVERED'
}

export enum ProductAvailabilityEnum {
  AVAILABLE = 'AVAILABLE',
  TEMPORARILY_UNAVAILABLE = 'TEMPORARILY_UNAVAILABLE',
  OUT_OF_STOCK = 'OUT_OF_STOCK'
}

export enum ProductBadgeEnum {
  NONE = 'NONE',
  NEW = 'NEW',
  POPULAR = 'POPULAR',
  DISCOUNT = 'DISCOUNT'
}

export enum SpecialEventTypeEnum {
  BIRTHDAY = 'BIRTHDAY',
  FRIDAY = 'FRIDAY',
  HOLIDAY = 'HOLIDAY',
  CAMPAIGN = 'CAMPAIGN'
}

export * from './constants.js';
